### ISSUE TITLE
message doesn't have text field

### ISSUE THREAD

**Issue by yonas-g** [KnorpelSenf/typegram#22]
I am having a problem getting a text from `ctx.message.text`. The error says "property 'text' does not exist on type..."

**Comment by KnorpelSenf** [comment]
I'm not sure this is the right place to ask the question. This library only provides types to bot frameworks, it does not concern itself with runtime things.

E.g. if you are using telegraf (the most popular consumer of this lib AFAIK), you should open an issue there.

Otherwise, it is not possible to say what the issue is, this depends on the type of `ctx` and the type of `ctx.message`. As an example, if your framework uses `Message` for the type of `ctx.message`, then you could narrow down the union via
```ts
if ('text' in ctx.message) {
  // ...
}
```

**Comment by wojpawlik** [comment]
See https://github.com/telegraf/telegraf/issues/1388#issuecomment-791573609
