### ISSUE TITLE
Different file content between typegram repos

### ISSUE THREAD

**Issue by misaelabanto** [KnorpelSenf/typegram#25]
The content of this file https://github.com/grammyjs/types/blob/main/update.d.ts if different of this other https://github.com/KnorpelSenf/typegram/blob/master/update.d.ts

My VS Code is not mapping the types correctly: it's only showing one prop

![image](https://user-images.githubusercontent.com/29669824/119243135-bafb0b80-bb29-11eb-87e7-93134cdbf8c2.png)

**Comment by KnorpelSenf** [comment]
The grammY types are an alternative way to model the Telegram API. Both ways are valid and have their pros and cons. The two repositories are not identical.

Main difference: The unions described in typegram's README are dropped for grammY. This improves tooling performance substantially for grammY, but it requires some sophisticated type transformations to achieve the same results.

This repository mirrors grammY's types in the way that changes to the Telegram API are first added to grammY, and then `git cherry-pick`ed back to typegram because it happens to be the case that the diff to previous versions is almost identical for both repos, despite the deviation between them.
